version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: patient-service-postgres
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - patient-service-network

volumes:
  postgres_data:

networks:
  patient-service-network:
    driver: bridge