version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: patient-service-postgres
    environment:
      POSTGRES_DB: patient_service_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - patient-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Patient Service Application
  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: patient_service_dev
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - patient-service-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  patient-service-network:
    driver: bridge